### ISSUE TITLE
MSVC LTO , gcc x86-64-v2 & x86-64-v3

### ISSUE THREAD

**Issue by CeruleanSky** [pineappleEA/pineapple-src#101]
I was wondering if this is keeping pace with the way the official builds of yuzu are being made as I saw on the[ latest progress report](https://yuzu-emu.org/entry/yuzu-progress-report-dec-2022/), yuzu said they achieved significant gains of 12% on Windows compiling with `LTO` with `MSVC`.   They also demonstrated a 7% boost by using  `x86-64-v2` with clang and gcc.  They had even better results with `x86-64-v3` but as 9% of the users can not use it, they are not using it by default.

So I was wondering if it isn't already being used, perhaps `MSVC LTO` builds could be released, and if `x86-64-v3` could also be made in addition so that 91% of the users could get a boost as well.

Their also seems to be a closed pull request  #55 that seems to be related to gcc lto and o3 , but not x86-64-v2 unless that is implied, and didn't seem to use MSVC LTO.

![image](https://user-images.githubusercontent.com/2829875/211684403-102d6199-b817-4e33-90c7-3c7b90e976fa.png)

**Comment by MGThePro** [comment]
That pull request was from when we still built our own linux appimages from source.

We don't anymore because it's too inconvenient. The builds in the release section are exactly the same as the ones patrons get.

You can use the source code from the repository to make your own build with more compiler optimizations (although I would recommend using the source archive from the windows zip in the release section because of some issues with my updating script), but it's not really something we're going to do on pineapple, especially since it can bring new bugs and instabilities.
