### ISSUE TITLE
Trying to make a updating sctipt

### ISSUE THREAD

**Issue by XDM-Inc** [pineappleEA/pineapple-src#105]
Im trying to make a app to download the latest appimage how would i start to make the script download the latest?

**Comment by MGThePro** [comment]
`curl -s https://api.github.com/repos/pineappleea/pineapple-src/releases | grep -o "https://.*.AppImage" | head -n1` 
Not the prettiest but should do the trick.

**Comment by XDM-Inc** [comment]
> 

interesting thanks , i see that puts a url, from here i just have to make it insert that url it grabs into a download.

**Comment by XDM-Inc** [comment]
Made one! thanks for step in the right direction @MGThePro   Here is a little something i whipped up, tested and working for arch linux and should work on others as well [Pineapple-Updater](https://github.com/XDM-Inc/-Pineapple-Updater)

**Comment by MGThePro** [comment]
@XDM-Inc Actually I just remembered, [liftinstall](https://github.com/pineappleEA/liftinstall) should be able to run on linux and install/update the appimages with just some config changes. Maybe it needs to be rebased to compile on linux though, not sure.

Shouldn't take much more than taking the [original linux config](https://github.com/yuzu-emu/liftinstall/blob/master/config.linux.v3.toml) and adapting the Early Access part to look like the mainline one, just with pinEApple links instead of pointing to the yuzu repo. I'm currently kinda busy so I don't think I'll be able to look at it for a while, but maybe you're interested. It shouldn't take any rust knowledge, I managed to do it the first time for windows without writing any rust code.

**Comment by MGThePro** [comment]
Ok as it turns out the people maintaining liftinstall know as much about rust as I do (nothing) and hit the same roadblock I did.

Their program literally cannot install yuzu unless it comes in an archive. It needs to through [this](https://github.com/pineappleEA/liftinstall/blob/master/src/archives/mod.rs) file, and if it's not a .zip or .tar.xz file it'll just fail. Guess I'll have to switch the backend from reuploading appimages to reuploading .tar.xz files and hope that nothing breaks.
