### ISSUE TITLE
Yuzu Lags on Latest Version

### ISSUE THREAD

**Issue by RootManHD** [pineappleEA/pineapple-src#155]
I'm experiencing a lot of lag in the latest versions of yuzu Master/EA. To make an example, if i try to run Super Mario Odyssey on yuzu EA 3769 it runs just fine at 55-60 fps, but if i run it on yuzu EA 3930 it gets really laggy and runs at 25-35 fps, anyone with this problem?

**Comment by SoftwareGuy** [comment]
It could be a regression. As this is only an outlet for re-uploading the EA builds from Yuzu's development pipeline, you'll unlikely get support here.

If you want support for mainline/EA releases, **support the devs** by paying the early access fee and then ask in their discord for assistance. Or use a different emulator.

Otherwise, use process of elimination. Start at version 3769 and then increment versions until you see performance drop. Then, work backwards. For example - start at 3769. Jump to 3800. If OK, continue jumping 10 builds until you find the one that causes the regression.

**Comment by MGThePro** [comment]
yes basically what the person above me said. Although if I were you I'd reproduce it on mainline and ask for support on that issue rather than pay their patreon fee
