### ISSUE TITLE
It may be a bug

### ISSUE THREAD

**Issue by Denfend** [pineappleEA/pineapple-src#156]
Hello, after several recent updates, except for the Kingdom of Tears, all other games crash. What could be the problem? Is it an issue with my settings or a bug in the updates?

**Comment by SoftwareGuy** [comment]
You won't get support for Yuzu Early Access here. This is only for redistribution of the EA builds. 

See if you can replicate the issue in Yuzu mainline. If you can do that, then go to their Discord and ask for help there, or file a bug ticket on their GitHub.

It is highly unlikely you'll get support from the Yuzu developers if you aren't a supporter. They tend to get a little edgy/upset when they see people getting their hands on Early Access builds without them being paid supporters (and there's nothing against that, since Yuzu is licensed under GPL-3).

**Comment by SoftwareGuy** [comment]
Just going to throw this tidbit from a previous issue ticket I commented on:

> Otherwise, use process of elimination. Start at version 3769 and then increment versions until you see the problem occuring. Then, work backwards. For example - start at 3769. Jump to 3800. If OK, continue jumping 10 builds until you find the one that causes the problem. Then, work backwards to identify which build introduced the issue.
