### ISSUE TITLE
Yuzu EA 4006 Zelda TOTK Crash

### ISSUE THREAD

**Issue by an00ra** [pineappleEA/pineapple-src#157]
When start Zelda TOTK always force close

**Comment by SoftwareGuy** [comment]
You won't get support for Yuzu Early Access here. This is only for redistribution of the EA builds.

See if you can replicate the issue in Yuzu mainline. If you can do that, then go to their Discord and ask for help there, or file a bug ticket on their GitHub.

It is unlikely you'll get support from the Yuzu developers if you aren't a supporter and haven't tried to test the games on mainline Yuzu first. They tend to get a little edgy/upset when they see people getting their hands on Early Access builds without them being paid supporters (and there's nothing against that, since Yuzu is licensed under GPL-3).

**Comment by SoftwareGuy** [comment]
Addendum: Make sure your device is up to date, ensure your GPU drivers are updated from official outlets (AMD/nVidia/Intel official websites, no driver update app garbage (they can do more harm than good), etc) and you have the latest firmware version + keys installed.
