### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by deezhizyu** [pineappleEA/pineapple-src#164]
Can I build yuzu early access from this repo? There is no submodules so CMake throwing errors

**Comment by MGThePro** [comment]
Ideally build it from the source archive in the windows releases.

**Comment by deezhizyu** [comment]
Thanks! Is that source is same as yuzu-emu/yuzu?

**Comment by MGThePro** [comment]
No, it's essentially the yuzu repo with some extra PRs merged.

The PRs in question are those with the "mainline-merge" and "earlyaccess-merge" tags on the yuzu repo.

Although there have been rare cases where an early access build has been launched with code that wasn't public otherwise yet (I believe that was the case with prometheus, the multicore implementation)

**Comment by deezhizyu** [comment]
So is it possible for me to get same source code, like in pineapple-src releases?

**Comment by MGThePro** [comment]
Kind of, but then you don't get nice stuff like the version or the commit hash. It's also a bit of a pain in the ass.

I have a tool for this on my account, the repo is called "yuzu-EA-compiler". It's a PKGBUILD for Arch Linux but it's essentially a glorified bash script. The thing you're looking for is the "prepare()" method.

It grabs all the Pull Requests with those tags and then tries to merge them in order. It doesn't always work because of merge conflicts, but usually it does. The rest of the PKGBUILD is super outdated so it probably wont compile properly, but the part for getting the source code should still work.

**Comment by deezhizyu** [comment]
Thanks! I will try source code from zip
