### ISSUE TITLE
Can't open FILE > INSTALL FILES TO NAND

### ISSUE THREAD

**Issue by benjamimgois** [pineappleEA/pineapple-src#24]
Hi, 

i'm using the yuzu EA appimage for linux version. Every time i try to open the FILE > INSTALL FILES TO NAND option (to install game updates) i got the error saying that ` /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache` doesn't exists, and the emulator closes. On my distro (Manjaro) i discover that this folder is located in  ` /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache`. 

To fix the issue i created a symbolic link to the folder with the command:
`sudo ln -s /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache`

Is it possible to include this fix in the next yuzu's appimage releases ?

**Comment by MGThePro** [comment]
Hmm, does the same issue happen when compiling yuzu with the [pineapple-linux](https://github.com/pineappleEA/Pineapple-Linux) script? If so, that's probably an issue with yuzu's source code (and they don't really like us submitting changes to their code). For the time being, you can alternatively use [this](https://github.com/dezem/SAK) tool to merge your updates into your game. In my experience installing files to nand hasn't been the most stable experience anyways in yuzu, but those issues I experienced are from some time ago, they might have fixed it since then.

**Comment by benjamimgois** [comment]
I just made a test and the same problem doesn't happen with the compiled version.

**Comment by P3rf3ctXZer0** [comment]
On Windows they don't even let you install to NAND anymore except for updates, are trying to install an update or a full game?

**Comment by benjamimgois** [comment]
> On Windows they don't even let you install to NAND anymore except for updates, are trying to install an update or a full game?

just an update.

**Comment by P3rf3ctXZer0** [comment]
Hm ... that is strange.

**Comment by MGThePro** [comment]
It should be fixed in the latest appimage release
