### ISSUE TITLE
Whats the auto-updater release?

### ISSUE THREAD

**Issue by HiDe-Techno-Tips** [pineappleEA/pineapple-src#39]
Whats [this](https://github.com/pineappleEA/pineapple-src/releases/latest)? How to use that?

And does this mean there will not be any more releases like the previous ones? (I mean the 7zip files)

**Comment by qurious-pixel** [comment]
Auto-Updater release will prompt you when a new version is available. 

The 7zip files will continue to populate as before in the non Auto-Updater release.

If you want a specific version, or to compare two versions, select the non Auto-Update.

**Comment by HiDe-Techno-Tips** [comment]
Releasing non standard app like this makes the repository look messy. There should have been a new branch for the auto-updater and the auto-updater releases should target that branch. This keeps things organized.

**Comment by Abyss777111** [comment]
when they have already added an update to the emulator itself

**Comment by MGThePro** [comment]
Could you elaborate? I'm not aware of any updater to yuzu itself, if that's what you meant.

There's [liftinstall](https://github.com/j-selby/liftinstall) and yuzu's fork to include their configuration, but that's for windows only (at least their fork is, regular liftinstall works on linux). We could potentially make liftinstall download appimages from pinEApple, but that would be a worse solution in my opinion, and it would require modification because liftinstall is only designed to work with certain archive formats. I've also dabbled in making liftinstall support pinEApple's windows releases, but sadly it doesnt support 7z/LZMA2 and I'm not experienced enough in rust to implement support for it myself.

**Comment by Nitmare64** [comment]
Hello. Can someone help with the auto update? I don’t know how to use it or where to put the image. Novice here.

**Comment by Abyss777111** [comment]
> Could you elaborate? I'm not aware of any updater to yuzu itself, if that's what you meant.
> 
> There's [liftinstall](https://github.com/j-selby/liftinstall) and yuzu's fork to include their configuration, but that's for windows only (at least their fork is, regular liftinstall works on linux). We could potentially make liftinstall download appimages from pinEApple, but that would be a worse solution in my opinion, and it would require modification because liftinstall is only designed to work with certain archive formats. I've also dabbled in making liftinstall support pinEApple's windows releases, but sadly it doesnt support 7z/LZMA2 and I'm not experienced enough in rust to implement support for it myself.

example of updating the second switch emulator
