### ISSUE TITLE
Reduced FPS performance after 2479 and beyond

### ISSUE THREAD

**Issue by Dban1** [pineappleEA/pineapple-src#51]
At 2478, I'm having 50\~55 FPS in Pokemon Legends Arceus, but after 2479 when there was changes to the texture_cache.h file, my FPS has dropped to 35\~44

**Comment by MGThePro** [comment]
Report this to the PR author instead, we're just releasing the builds, not touching any source code.

[Here's](https://github.com/yuzu-emu/yuzu/pull/7840) the PR that made the change in 2479.

Also, they probably want you to test a build with just that PR merged instead of the full early access build. So you'll need to figure out how to build yuzu from source code.

**Comment by Dban1** [comment]
>  test a build with just that PR merged

Oh you mean they might ask me to do this to substantiate my claims / confirm the problem is with that PR?

**Comment by MGThePro** [comment]
Yea that and they don't want to support people who used Early Access builds without paying.

**Comment by Dban1** [comment]
I see. Also I'm curious what is the difference between the EA builds and just building directly from the main yuzu source code?

**Comment by MGThePro** [comment]
The Early Access builds contain all pull requests with the [early-access-merge label](https://github.com/yuzu-emu/yuzu/pulls?q=is%3Apr+is%3Aopen+label%3Aearly-access-merge) as well as the [mainline-merge label](https://github.com/yuzu-emu/yuzu/pulls?q=is%3Apr+is%3Aopen++label%3Amainline-merge+). Mainline builds only include the PRs with the mainline-merge label, and building the source code from the yuzu repo doesn't contain any additional PRs at all.
