### ISSUE TITLE
Empty update for 2494?

### ISSUE THREAD

**Issue by Dban1** [pineappleEA/pineapple-src#53]
I was comparing 2494 and 2493 and the only thing that changed was the README. Just curious if this was normal?

**Comment by MGThePro** [comment]
Yea that's normal, and works as intended. Some updates from yuzu are just empty. I'm assuming that's because their CI gets triggered when a PR that was originally in early access but not in master gets merged. The CI creates a new build because there had been a change, but the early access source code hasn't changed.
