### ISSUE TITLE
yuzu not load anymore

### ISSUE THREAD

**Issue by CodingBDX** [pineappleEA/pineapple-src#54]
hello:

i use it since 2 days, and after 3 days i have, it's message, but i touch nothing else...please help me

Package gdk-pixbuf-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gdk-pixbuf-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gdk-pixbuf-2.0' found
mv: /tmp/.mount_yuzu-xeNNBlu/usr/lib/libselinux.so.1: no version information available (required by mv)
Qt Concurrent has caught an exception thrown from a worker thread.
This is not supported, exceptions thrown in worker threads must be
caught before control returns to Qt Concurrent.
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: status: Permission non accordée [/media/kiki/Elements/jeux/switch]
/tmp/.mount_yuzu-xeNNBlu/AppRun : ligne 17 : 106360 Abandon                 $APPDIR/AppRun-patched

**Comment by MGThePro** [comment]
Is that from the appimage release?

**Comment by CodingBDX** [comment]
Hello, yes from thé last 2 releases appimage...
But i think, i mount my folder and unmount it, it's thé problème???

**Comment by MGThePro** [comment]
Yea my next guess would've been permissions
`filesystem error: status: Permission non accordée [/media/kiki/Elements/jeux/switch]`
I don't know french, but that sounds like it can't access your switch folder.

So maybe try changing ownership and permissions of that folder with `chown` and `chmod`

**Comment by CodingBDX** [comment]
yes i see but it's problem because my folder are change, it's >Elements1 not Element but yuzu search again into Element...
where i can configuration that?
thank

**Comment by MGThePro** [comment]
Oh, hmm. If I understand you correctly, you renamed your Elements folder, which yuzu used to scan for your games in, and now it's still scanning in Elements instead of the new name?

In that case, you can remove the old folder name by right clicking it.
![Screenshot_20220224_000926](https://user-images.githubusercontent.com/17652761/155425151-5970c476-7a32-452f-bdcc-a65cc1cf7a92.png)
And then double click on "Add New Game Directory" to add your new games directory
