### ISSUE TITLE
Cant enable portable mode with appimage ver

### ISSUE THREAD

**Issue by XDM-Inc** [pineappleEA/pineapple-src#61]
portable mode does not work when using the appimage version of yuzu.

**Comment by MGThePro** [comment]
yuzu's portable mode wont work with the Appimage, because it expects the necessary files to be next to the yuzu executable, which is in a read only squashfs inside the Appimage. Appimages however have their own portable mode that works similarly.

Next to your appimage, create a folder called `yuzu-x86_64.AppImage.home`. Rename the first part if your Appimage has a different name. Inside this folder will be a .config and a .local folder, in which you can put your config, keys, and games. yuzu will treat these like they were in ~/.config and ~/.local

**Comment by XDM-Inc** [comment]
thanks! that good enough for me.
